// This is the '.h' file for 'AStar3DPostProcessor', the module that handles tracks generated by the 'AStar3D' algorithm after they have been tagged.
// 

#include 


namespace larlitecv {

  std::vector< BMTrackCluster3D > AStar3DPostProcessor::separateAStarTracks(std::vector < BMTrackCluster >& tracks_v, double maximum_distance, const std::vector<larcv::Image2D>& imgs, const std::vector<larcv::Image2D>& badchimgs, const std::vector<float>& thresholds, const std::vector<int>& neighborhood_size);

}
